# -*- coding: utf-8 -*-
"""task1__data_collection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYBbODWNJqYm8VF67weWT5wr1WwSGDI5
"""

import requests
import time
from datetime import datetime # current date and time
import json
import os  # folder creation

# fetching each story id datas ( step - 1)
url = "https://hacker-news.firebaseio.com/v0/topstories.json"

response = requests.get(url)  # fetech data is stored in the response varaiable

data = response.json() # data it turns json formate

headers = {"User-Agent": "TrendPulse/1.0"}

stories=[] # create empty list to hold needed datas ( step - 2)

category_count = {  # category count intiallization
    "technology": 0,
    "weather": 0,
    "sports": 0,
    "science": 0,
    "entertainment": 0,
    "others": 0
}

for story_id in data[:500]:
    story_url = f"https://hacker-news.firebaseio.com/v0/item/{story_id}.json"
    story_response = requests.get(story_url,headers=headers)
    story = story_response.json()

    time.sleep(1)

    if story and story.get("title"):

# assing lower case for categorization
        title = story.get("title")
        title_lower = title.lower()

# catergorization
        if any(k in title_lower for k in ["ai", "data", "api", "software", "tech", "programming"]):
          category = "technology"

        elif any(k in title_lower for k in ["climate", "weather", "rain", "storm", "temperature"]):
            category = "weather"

        elif any(k in title_lower for k in ["player", "match", "team", "cricket", "football", "nba"]):
             category = "sports"

        elif any(k in title_lower for k in ["study", "research", "science", "experiment", "physics", "biology"]):
             category = "science"

        elif any(k in title_lower for k in ["movie", "film", "music", "book", "show", "ticket"]):
              category = "entertainment"

        else:
             category = "others"

# extract the fields

        if category_count[category] < 25:           # limit 25 per category

              stories.append({
                  "post_id" : story.get("id"),
                  "title" : title,
                  "category" : category,
                  "score" : story.get("score"),
                  "num_comments" : story.get("descendants"),
                  "author" : story.get("by"),
                  "collected_at" : datetime.now().strftime("%Y-%m-%d %H:%M:%S")
      })
              category_count[category] += 1

    if sum(category_count.values()) >= 500:
         break


print("Counts of Category :", category_count)

if stories:
      print(stories[0])

# save to a json file(step - 3)

os.makedirs("data",exist_ok = True)                                # creat folder name

filename = f"data/trends_{datetime.now().strftime("%Y%m%d")}.json" # creat file name

with open(filename , "w" , encoding="utf-8") as f:                 # save to json file
  json.dump(stories,f,indent=4,ensure_ascii=False)


# output

print("Data saved sucessfully!")
print("✅ Total stories collected:", len(stories))
print("📊 Category count:", category_count)
print("📁 Saved to:", filename)