# -*- coding: utf-8 -*-
"""task3_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqCorepSBG4hh24x7YVCSdjS9D8rM_M3
"""

from google.colab import files
uploaded = files.upload()

#task 1 — Load and Explore
import pandas as pd
import numpy as np

# load saved csv datas in pd dataframe

df = pd.read_csv("trends_clean.csv")
print(df)

print("First 5 rows :",df.head())
print("Shape of the DataFrame:",df.shape)
print("Average score of all stories:",df["score"].mean().round(2))
print("num_comments of all stories:",df["num_comments"].mean().round(2))

# task 2 -  Basic Analysis with NumPy
import numpy as np

print("Average of score:",np.mean(df["score"]).round(2))
print("Median of score:",np.median(df["score"]).round(2))
print("Standard deviation of score:",np.std(df["score"]))
print("Maximum of score:",np.max(df["score"]))
print("Minimum of score:",np.min(df["score"]))

import numpy as np

categories = df["category"].values

unique, counts = np.unique(categories, return_counts=True)

max_index = np.argmax(counts)

print("Most stories category:", unique[max_index])
print("Number of stories:", counts[max_index])

max_row = df.loc[df["num_comments"].idxmax()]
print("Most comments of story:",max_row["num_comments"])
print("Title :",max_row["title"])

#task 3 — Add New Columns

df["engagement"] = df["num_comments"]/(df["score"]+1).round(2)
print(df["engagement"])

df["is_popular"] = df["score"] > np.mean(df["score"])
print(df["is_popular"])

print(df)

# Output summary

print(f"Loaded data:,{df.shape}\n")
print(f"First five rows:,{df.head()}\n")

print("--------Numpy Status----------\n")
print("Average of score:",np.mean(df["score"]).round(2))
print("Median of score:",np.median(df["score"]).round(2))
print("Standard deviation of score:",np.std(df["score"]))
print("Maximum of score:",np.max(df["score"]))
print(f"Minimum of score:{np.min(df["score"])}\n")

print("Most stories category:", unique[max_index])
print(f"Number of stories: {counts[max_index]}\n")

print("Most comments of story:",max_row["num_comments"])
print(f"Title :{max_row["title"]}\n")

# save the final analyse data

df.to_csv("trends_analysed.csv",index=False)
print("File saved successfully to data/trends_analysed.csv")