# -*- coding: utf-8 -*-
"""task2_data_processing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2RqH3biJZO1c0gesMvwFjPt6IYwTNT9
"""

from google.colab import files
uploaded = files.upload()  # pick your JSON file from local

import json
import pandas as pd

# task - 1  Load the JSON File

with open("trends_20260409.json" , "r" , encoding="utf-8") as file:
  data = json.load(file)

  df = pd.DataFrame(data)
  print(df)
  print(df.shape)

print(df.info())

# task 2 — Clean the Data

# remove dupilcates
print(df.isnull().sum())
print(df.duplicated())

df["score"] = pd.to_numeric(df["score"],errors = "coerce") # remove stories where score is less than 5
df = df[df["score"] >= 5]

df['title'] = df['title'].str.strip() # strip extra spaces from the title column
print("After cleaning data =",df.shape[0])

# save this file as csv format

df.to_csv("trends_clean.csv", index = False ,encoding="utf-8")

import os
print(os.listdir())  # should show 'trends_clean.csv'

# summary output
print(f"Total stories loaded: {len(df)}\n")
print("\nStories per category:\n")
print(df['category'].value_counts())
print(f"\nSaved stories : {df.shape[0]}")
print("There is no null values exits")